export enum TimerSettings {
  TWENTY_MINUTES = 1200,
  BREAK_TIME = 20,
  STROKE_LENGTH = 595,
  SMALL_SCREEN = 768,
  NOTIFICATION_BREAK_START = 'Break time starts',
  NOTIFICATION_BREAK_FINISH = 'Break time is over!',
  NOTIFICATION_DISPLAY_TIME = 5000,
}
